/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  theme: {
    extend: {
      fontFamily: {
        heading: ["'Brygada 1918'", "Georgia", "serif"],
        display: ["'Brygada 1918'", "Georgia", "serif"],
        body: ["'DM Sans'", "sans-serif"],
        ui: ["'DM Sans'", "sans-serif"],
      },
      colors: {
        background: "var(--bg-base)",
        foreground: "var(--text-main)",
        card: { DEFAULT: "var(--bg-white)", foreground: "var(--text-main)" },
        popover: { DEFAULT: "var(--bg-white)", foreground: "var(--text-main)" },
        primary: { DEFAULT: "var(--orange-500)", foreground: "#fff" },
        secondary: { DEFAULT: "var(--green-700)", foreground: "#fff" },
        muted: { DEFAULT: "var(--bg-base)", foreground: "var(--text-sec)" },
        accent: { DEFAULT: "var(--orange-50)", foreground: "var(--text-main)" },
        destructive: { DEFAULT: "#D7392F", foreground: "#fff" },
        border: "var(--border)",
        input: "var(--border)",
        ring: "var(--orange-500)",
        green: {
          50: "var(--green-50)",
          100: "var(--green-100)",
          200: "var(--green-200)",
          300: "var(--green-300)",
          400: "var(--green-400)",
          500: "var(--green-500)",
          600: "var(--green-600)",
          700: "var(--green-700)",
          800: "var(--green-800)",
          900: "var(--green-900)",
        },
        orange: {
          50: "var(--orange-50)",
          100: "var(--orange-100)",
          200: "var(--orange-200)",
          300: "var(--orange-300)",
          400: "var(--orange-400)",
          500: "var(--orange-500)",
          600: "var(--orange-600)",
          700: "var(--orange-700)",
        },
        carbon: "var(--carbon)",
        whatsapp: "var(--whatsapp)",
        ink: "var(--text-main)",
        bone: "var(--bg-base)",
        sand: "#EFEAE1",
        sage: { DEFAULT: "#6B705C" },
        jade: { DEFAULT: "var(--green-700)" },
        terracotta: { DEFAULT: "var(--orange-500)", hover: "var(--orange-600)" },
        sun: { DEFAULT: "#FFB627" },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 4px)",
        sm: "calc(var(--radius) - 8px)",
      },
      boxShadow: {
        soft: "0 6px 24px rgba(45,90,27,0.06)",
        floating: "0 18px 38px rgba(44,44,42,0.10)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
